version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test:
    docker:
      - image: cimg/ruby:2.6.8
        environment:
          DATABASE_URL: postgresql://circleci@localhost/circle_test
          ENV: CIRCLE
      - image: cimg/postgres:14.0
    environment:
      PGHOST: localhost
      PGUSER: circleci
      POSTGRES_USER: postgres
      POSTGRES_DB: circle_test
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: ""
    services:
      - postgresql
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v

      - run: gem install bundler
      - run: bundle install --path vendor/bundle
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Create schema
          command: |
            CREATE SCHEMA [IF NOT EXISTS] Pets
            CREATE TABLE owners (id, owner)
            CREATE TABLE pets (id, type, name, gender, neutered, owner_id)

      - run:
          command: bundle exec rspec
      # - run:
      # command: bundle config set --local path 'vendor/bundle'

workflows:
  build_and_test_deploy:
    jobs:
      - build_and_test
      - heroku/deploy-via-git:
          requires:
            - build_and_test
